file_format: "1"
id: onesplitwonder
name: onesplitwonder
type: shield
url: https://github.com/RobinD2001/zmk-config-onesplitwonder
requires: [nice_nano]
features:
  - keys
siblings:
  - onesplitwonder_left
  - onesplitwonder_right
